
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2012
Project("{99DDE922-26B8-45F6-9776-7310255F16BA}") = "test_form_src", "test_form_src.sfproj", "{CFE9622E-69BC-43BD-9E89-F3F2380FA306}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x86 = Debug|x86
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{CFE9622E-69BC-43BD-9E89-F3F2380FA306}.Debug|x86.ActiveCfg = Debug|x86
		{CFE9622E-69BC-43BD-9E89-F3F2380FA306}.Debug|x86.Build.0 = Debug|x86
		{CFE9622E-69BC-43BD-9E89-F3F2380FA306}.Release|x86.ActiveCfg = Debug|x86
		{CFE9622E-69BC-43BD-9E89-F3F2380FA306}.Release|x86.Build.0 = Debug|x86
	EndGlobalSection
EndGlobal
